//
//  Cuisine.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class Cuisine: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _cuisineId: String?
    var _cuisine: String?
    var _imageKey: String?
    
    class func dynamoDBTableName() -> String {

        return "project-mobilehub-2093181805-Cuisine"
    }
    
    class func hashKeyAttribute() -> String {

        return "_cuisineId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_cuisineId" : "cuisineId",
               "_cuisine" : "cuisine",
               "_imageKey" : "imageKey",
        ]
    }
}
