//
//  Recipes.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

@objcMembers
class Recipes: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _recipeId: String?
    var _authorFullName: String?
    var _cookingTime: String?
    var _cuisine: String?
    var _description: String?
    var _imageKey: String?
    var _ingredients: String?
    var _methodOfPreparation: String?
    var _servesTo: String?
    var _title: String?
    var _totalUserRatings: NSNumber?
    var _totalUsersRated: NSNumber?
    var _totalViews: NSNumber?
    var _userId: String?
    var _videoKey: String?
    
    class func dynamoDBTableName() -> String {
        
        return "project-mobilehub-2093181805-Recipes"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_recipeId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_recipeId" : "recipeId",
            "_authorFullName" : "authorFullName",
            "_cookingTime" : "cookingTime",
            "_cuisine" : "cuisine",
            "_description" : "description",
            "_imageKey" : "imageKey",
            "_ingredients" : "ingredients",
            "_methodOfPreparation" : "methodOfPreparation",
            "_servesTo" : "servesTo",
            "_title" : "title",
            "_totalUserRatings" : "totalUserRatings",
            "_totalUsersRated" : "totalUsersRated",
            "_totalViews" : "totalViews",
            "_userId" : "userId",
            "_videoKey" : "videoKey",
        ]
    }
}
